stages:
  - validate
  - plan
  - deploy
  - destroy

variables:
  TF_ROOT: "infra"
  TF_VERSION: "1.5.7"
  AWS_REGION: "eu-west-3"

image: alpine/terragrunt:latest

before_script:
  - cd $TF_ROOT
  - terraform --version
  - terraform init -input=false

validate:
  stage: validate
  script:
    - terraform fmt -check
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - $TF_ROOT/tfplan
      - $TF_ROOT/terraform.tfstate
      - $TF_ROOT/terraform.tfstate.backup
    expire_in: 1 hour

apply:
  stage: deploy
  script:
    - terraform apply -auto-approve tfplan
  artifacts:
    paths:
      - $TF_ROOT/terraform.tfstate
      - $TF_ROOT/terraform.tfstate.backup
    expire_in: 1 hour
  when: manual
  dependencies:
    - plan

destroy:
  stage: destroy
  script:
    - terraform destroy -auto-approve
  when: manual
  dependencies:
    - apply
